/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.github.elgleidson.jackson.problem;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@org.apache.avro.specific.AvroGenerated
public class MyAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4587814141294862806L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MyAvro\",\"namespace\":\"com.github.elgleidson.jackson.problem\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"xTransactionId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"xxTransactionId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<MyAvro> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<MyAvro> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<MyAvro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<MyAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<MyAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this MyAvro to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a MyAvro from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a MyAvro instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static MyAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String id;
  private java.lang.String xTransactionId;
  private java.lang.String xxTransactionId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MyAvro() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param xTransactionId The new value for xTransactionId
   * @param xxTransactionId The new value for xxTransactionId
   */
  public MyAvro(java.lang.String id, java.lang.String xTransactionId, java.lang.String xxTransactionId) {
    this.id = id;
    this.xTransactionId = xTransactionId;
    this.xxTransactionId = xxTransactionId;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return xTransactionId;
    case 2: return xxTransactionId;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = value$ != null ? value$.toString() : null; break;
    case 1: xTransactionId = value$ != null ? value$.toString() : null; break;
    case 2: xxTransactionId = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'xTransactionId' field.
   * @return The value of the 'xTransactionId' field.
   */
  public java.lang.String getXTransactionId() {
    return xTransactionId;
  }


  /**
   * Sets the value of the 'xTransactionId' field.
   * @param value the value to set.
   */
  public void setXTransactionId(java.lang.String value) {
    this.xTransactionId = value;
  }

  /**
   * Gets the value of the 'xxTransactionId' field.
   * @return The value of the 'xxTransactionId' field.
   */
  public java.lang.String getXxTransactionId() {
    return xxTransactionId;
  }


  /**
   * Sets the value of the 'xxTransactionId' field.
   * @param value the value to set.
   */
  public void setXxTransactionId(java.lang.String value) {
    this.xxTransactionId = value;
  }

  /**
   * Creates a new MyAvro RecordBuilder.
   * @return A new MyAvro RecordBuilder
   */
  public static com.github.elgleidson.jackson.problem.MyAvro.Builder newBuilder() {
    return new com.github.elgleidson.jackson.problem.MyAvro.Builder();
  }

  /**
   * Creates a new MyAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new MyAvro RecordBuilder
   */
  public static com.github.elgleidson.jackson.problem.MyAvro.Builder newBuilder(com.github.elgleidson.jackson.problem.MyAvro.Builder other) {
    if (other == null) {
      return new com.github.elgleidson.jackson.problem.MyAvro.Builder();
    } else {
      return new com.github.elgleidson.jackson.problem.MyAvro.Builder(other);
    }
  }

  /**
   * Creates a new MyAvro RecordBuilder by copying an existing MyAvro instance.
   * @param other The existing instance to copy.
   * @return A new MyAvro RecordBuilder
   */
  public static com.github.elgleidson.jackson.problem.MyAvro.Builder newBuilder(com.github.elgleidson.jackson.problem.MyAvro other) {
    if (other == null) {
      return new com.github.elgleidson.jackson.problem.MyAvro.Builder();
    } else {
      return new com.github.elgleidson.jackson.problem.MyAvro.Builder(other);
    }
  }

  /**
   * RecordBuilder for MyAvro instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MyAvro>
    implements org.apache.avro.data.RecordBuilder<MyAvro> {

    private java.lang.String id;
    private java.lang.String xTransactionId;
    private java.lang.String xxTransactionId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.github.elgleidson.jackson.problem.MyAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.xTransactionId)) {
        this.xTransactionId = data().deepCopy(fields()[1].schema(), other.xTransactionId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.xxTransactionId)) {
        this.xxTransactionId = data().deepCopy(fields()[2].schema(), other.xxTransactionId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing MyAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(com.github.elgleidson.jackson.problem.MyAvro other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.xTransactionId)) {
        this.xTransactionId = data().deepCopy(fields()[1].schema(), other.xTransactionId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.xxTransactionId)) {
        this.xxTransactionId = data().deepCopy(fields()[2].schema(), other.xxTransactionId);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.String getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.github.elgleidson.jackson.problem.MyAvro.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.github.elgleidson.jackson.problem.MyAvro.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'xTransactionId' field.
      * @return The value.
      */
    public java.lang.String getXTransactionId() {
      return xTransactionId;
    }


    /**
      * Sets the value of the 'xTransactionId' field.
      * @param value The value of 'xTransactionId'.
      * @return This builder.
      */
    public com.github.elgleidson.jackson.problem.MyAvro.Builder setXTransactionId(java.lang.String value) {
      validate(fields()[1], value);
      this.xTransactionId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'xTransactionId' field has been set.
      * @return True if the 'xTransactionId' field has been set, false otherwise.
      */
    public boolean hasXTransactionId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'xTransactionId' field.
      * @return This builder.
      */
    public com.github.elgleidson.jackson.problem.MyAvro.Builder clearXTransactionId() {
      xTransactionId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'xxTransactionId' field.
      * @return The value.
      */
    public java.lang.String getXxTransactionId() {
      return xxTransactionId;
    }


    /**
      * Sets the value of the 'xxTransactionId' field.
      * @param value The value of 'xxTransactionId'.
      * @return This builder.
      */
    public com.github.elgleidson.jackson.problem.MyAvro.Builder setXxTransactionId(java.lang.String value) {
      validate(fields()[2], value);
      this.xxTransactionId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'xxTransactionId' field has been set.
      * @return True if the 'xxTransactionId' field has been set, false otherwise.
      */
    public boolean hasXxTransactionId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'xxTransactionId' field.
      * @return This builder.
      */
    public com.github.elgleidson.jackson.problem.MyAvro.Builder clearXxTransactionId() {
      xxTransactionId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public MyAvro build() {
      try {
        MyAvro record = new MyAvro();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.xTransactionId = fieldSetFlags()[1] ? this.xTransactionId : (java.lang.String) defaultValue(fields()[1]);
        record.xxTransactionId = fieldSetFlags()[2] ? this.xxTransactionId : (java.lang.String) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<MyAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<MyAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<MyAvro>
    READER$ = (org.apache.avro.io.DatumReader<MyAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.id);

    out.writeString(this.xTransactionId);

    out.writeString(this.xxTransactionId);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readString();

      this.xTransactionId = in.readString();

      this.xxTransactionId = in.readString();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readString();
          break;

        case 1:
          this.xTransactionId = in.readString();
          break;

        case 2:
          this.xxTransactionId = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










